### ISSUE TITLE
Rendering PlantUml at Live Mkdocs pages

### ISSUE THREAD

**Issue by rpaut** [christo-ph/mkdocs_build_plantuml#1]
Hello,

Pip installed mkdocs-plantuml package and add plugin example to mkdocs.yml.
How to call and type PlantUml at live pages ?

```plantuml

Alice->Bob: Hello Bob, how are you? 

Note right of Bob: Bob thinks

Bob-->Alice: I am good thanks!

```
Does not render PlantUml image at mkdocs pages. Do you have live example available?

**Comment by christo-ph** [comment]
Hi @rpaut 

This plugin does not render Plantuml embedded in Markdown files. In does generate the images from pure Plantuml files (.puml, starting with @startuml etc).

If you want to have the images rendered embed in the Markdown file itself, you need another plugin, see:

https://github.com/mkdocs/mkdocs/issues/901

You need to have installed https://github.com/mikitex70/plantuml-markdown to get it to work. Then you are able to do something like this in your .md file:

````
```plantuml format="png" classes="uml myDiagram" alt="My super diagram placeholder" title="My super diagram" width="300px" height="300px"
  Goofy ->  MickeyMouse: calls
  Goofy <-- MickeyMouse: responds
```
````

The reason for this plugin was to have the diagrams separated from the markdown files. And to structure the output to my needs as descreibed in the README.
