### ISSUE TITLE
Add support for include folders

### ISSUE THREAD

**Issue by yababer** [christo-ph/mkdocs_build_plantuml#12]
It would be awesome if there was support to add other folders to search for !include files.

Something similar to support in vscode:  https://github.com/qjebbs/vscode-plantuml

```
plantuml.includepaths: Specifies the include paths besides source folder and the diagramsRoot.
```

**Comment by christo-ph** [comment]
Hi @yababer I am currently too busy to add functionality here.

Accepting Merge Requests.

**Comment by yababer** [comment]
sounds good, if I have a bit of time this weekend I will push something up.

**Comment by yababer** [comment]
@christo-ph I had a few minutes and added this feature.  Can you give me access so I can create a pr.

**Comment by yababer** [comment]
We ended up forking the plugin in our local repo and made changes there.  Let us know if you want to push it back here, I will close this issue for now.

**Comment by christo-ph** [comment]
Sorry, I missed you last message. You should simply make an merge request, this should work.

**Comment by christo-ph** [comment]
To work properly, you should fork from GitHub directly. Work on the code and then make the pull request. I suppose, you were working by cloning this repo?

**Comment by christo-ph** [comment]
Anyway, you should now be able to push

**Comment by christo-ph** [comment]
Thanks @yababer , I merged your pull request.

Would be nice if you also add the new behavior to the README.md in the root folder.
