### ISSUE TITLE
Using C4 with includes outputs error

### ISSUE THREAD

**Issue by jevin36** [christo-ph/mkdocs_build_plantuml#2]
Hi, I am using C4 (https://github.com/RicardoNiepel/C4-PlantUML ) in combination with plantUML locally (not server mode). My plantuml file looks like this:

```
@startuml C4_Elements
!include /C4/C4_Container.puml

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")
@enduml
```
The C4 Model file are based in the /C4 directory. I also added the path to the includes in the C4 model files.

The mkdocs build process outputs the following messages:

```
Could not open /C4/e C4.puml
Could not open /C4/e C4_Context.puml
```
Most of the time although this is printed out the resulting svg is generated.

**Comment by christo-ph** [comment]
Hi. Thank you for your report.

The mentioned output is due to the not supporting `!includeurl`in server mode, which should not be printed when using the `local` mode. I have to remove this error here.

The output (svg/png) should work locally anyway. Can you confirm that?

**Comment by christo-ph** [comment]
Release 1.2.0

Please update your plugin and test the behaviour now:

`pip3 install --upgrade mkdocs-build-plantuml-plugin`

**Comment by jevin36** [comment]
Hi,
thanks a lot! I just tested it successfully.

**Comment by christo-ph** [comment]
Great. You could use C4 now also with `!includeurl` in server mode.
