### ISSUE TITLE
Output folders on Windows

### ISSUE THREAD

**Issue by jjliston** [christo-ph/mkdocs_build_plantuml#5]
I am using MkDocs with mkdocs-build-plantuml-plugin on a Windows device. Everything seems to work well except that the output folder structure does not mirror the input folder structure as documented. When files are stored in the `input_folder`, their images are generated to the `output_folder`. But when files are stored in a subfolder of `input_folder`, their images are generated to a like-named subfolder of `C:/`. 

Example...

```
c:/
    my-project/
        docs/
            diagrams/
                out/
                    file.svg
                src/
                    file.puml
                    subdir1/
                        file1.puml
    subdir1/
        file1.svg
```

I am not a Python developer but I believe the cause of the issue to be at line 47 of plantuml.py.

```python
diagram.out_dir = os.path.join(os.getcwd(), self.config['diagram_root'], self.config['output_folder'],*subdir.replace(root_input,"").split("/"))
```

The last function call, `split("/")` doesn't work on Windows. If does work if you replace it with `split(os.sep)`.

**Comment by christo-ph** [comment]
Hi,

Thanks for you report. Did you already test this? Do you want to make a merge request?

If not I will do this asap.

**Comment by jjliston** [comment]
I tested it locally on my Windows device. I'd be happy to submit a merge request if you can test it on non-Windows devices.

**Comment by christo-ph** [comment]
HI,

yes, I could test it on OS X and Linux.
